python audiobook.py book.txt

Тепер усе має запрацювати. Якщо виникнуть інші помилки, покажіть вивід — розберемося далі.

DeepThink
AI-generated, for reference only
~/Документи/Неназвана тека ❯ python3 audiobook.py book.txt ❌ edge-tts не установлен. Запусти: pip install edge-tts ~/Документи/Неназвана тека ❯ pip install edge-tts error: externally-managed-environment × This environment is externally managed ╰─> To install Python packages system-wide, try 'pacman -S python-xyz', where xyz is the package you are trying to install. If you wish to install a non-Arch-packaged Python package, create a virtual environment using 'python -m venv path/to/venv'. Then use path/to/venv/bin/python and path/to/venv/bin/pip. If you wish to install a non-Arch packaged Python application, it may be easiest to use 'pipx install xyz', which will manage a virtual environment for you. Make sure you have python-pipx installed via pacman. note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages. hint: See PEP 668 for the detailed specification. ~/Документи/Неназвана тека ❯ sudo pip install edge-tts [sudo] пароль до vitalij: error: externally-managed-environment × This environment is externally managed ╰─> To install Python packages system-wide, try 'pacman -S python-xyz', where xyz is the package you are trying to install. If you wish to install a non-Arch-packaged Python package, create a virtual environment using 'python -m venv path/to/venv'. Then use path/to/venv/bin/python and path/to/venv/bin/pip. If you wish to install a non-Arch packaged Python application, it may be easiest to use 'pipx install xyz', which will manage a virtual environment for you. Make sure you have python-pipx installed via pacman. note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages. hint: See PEP 668 for the detailed specification. ~/Документи/Неназвана тека ❯
~/Документи/Неназвана тека ❯ python3 -m venv venv ~/Документи/Неназвана тека ❯ source venv/bin/activate venv/bin/activate (line 40): 'case' builtin not inside of switch block case "$(uname)" in ^~~^ from sourcing file venv/bin/activate source: Error while reading file 'venv/bin/activate' ~/Документи/Неназвана тека ❯
venv ❯ python audiobook.py book.txt Traceback (most recent call last): File "/usr/lib/python3.14/argparse.py", line 1748, in _check_help formatter._expand_help(action) ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^ File "/usr/lib/python3.14/argparse.py", line 676, in _expand_help return help_string % params ~~~~~~~~~~~~^~~~~~~~ ValueError: unsupported format character ''' (0x27) at index 20 The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/home/vitalij/Документи/Неназвана тека/audiobook.py", line 553, in <module> main() ~~~~^^ File "/home/vitalij/Документи/Неназвана тека/audiobook.py", line 406, in main parser.add_argument("--rate", "-r", default="", ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help="Скорость речи: '+20%', '-10%' и т.д.") ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/lib/python3.14/argparse.py", line 1562, in add_argument self._check_help(action) ~~~~~~~~~~~~~~~~^^^^^^^^ File "/usr/lib/python3.14/argparse.py", line 1750, in _check_help raise ValueError('badly formed help string') from exc ValueError: badly formed help string ~/Документи/Н
