locate "*.md" > список_md.txt

После выполнения проверьте содержимое файла командой cat список_файлов.txt или откройте в текстовом редакторе.

/home/vitalij/.config/micro/syntax/README.md
/home/vitalij/.config/heroic/tools/dxvk-nvapi/dxvk-nvapi-v0.9.0/README.md
/home/vitalij/.config/heroic/tools/dxvk-nvapi/dxvk-nvapi-v0.9.1/README.md
/home/vitalij/.local/share/lutris/runtime/dxvk-nvapi/v0.9.0/README.md
/home/vitalij/.local/share/lutris/runtime/gamecontrollerdb/README.md
/home/vitalij/.local/share/nvm/v18.20.8/CHANGELOG.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/README.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/docs/content/commands/npm-edit.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/docs/content/commands/npm-whoami.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/docs/content/commands/npm-link.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/docs/content/commands/npm-rebuild.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/docs/content/commands/npm-install.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/docs/content/commands/npm-explain.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/docs/content/commands/npm-fund.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/docs/content/commands/npm-help.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/docs/content/commands/npm-pkg.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/docs/content/commands/npm-view.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/docs/content/commands/npm-shrinkwrap.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/docs/content/commands/npm-repo.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/docs/content/commands/npm-dedupe.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/docs/content/commands/npm-update.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/docs/content/commands/npm-token.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/docs/content/commands/npm-init.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/docs/content/commands/npm-publish.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/docs/content/commands/npm-team.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/docs/content/commands/npm-sbom.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/docs/content/commands/npm-unpublish.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/docs/content/commands/npm-pack.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/docs/content/commands/npm-prefix.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/docs/content/commands/npm-stars.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/docs/content/commands/npm-start.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/docs/content/commands/npm-stop.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/docs/content/commands/npm-test.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/docs/content/commands/npm-uninstall.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/docs/content/commands/npm-unstar.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/docs/content/commands/npm-version.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/docs/content/commands/npm-find-dupes.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/docs/content/commands/npm-access.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/docs/content/commands/npm-doctor.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/docs/content/commands/npm-diff.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/docs/content/commands/npm-adduser.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/docs/content/commands/npm-explore.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/docs/content/commands/npm-help-search.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/docs/content/commands/npm-login.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/docs/content/commands/npm-prune.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/docs/content/commands/npm-run-script.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/docs/content/commands/npm-completion.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/docs/content/commands/npx.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/docs/content/commands/npm-cache.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/docs/content/commands/npm-dist-tag.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/docs/content/commands/npm-bugs.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/docs/content/commands/npm-docs.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/docs/content/commands/npm-profile.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/docs/content/commands/npm.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/docs/content/commands/npm-ci.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/docs/content/commands/npm-config.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/docs/content/commands/npm-install-ci-test.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/docs/content/commands/npm-install-test.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/docs/content/commands/npm-exec.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/docs/content/commands/npm-restart.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/docs/content/commands/npm-root.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/docs/content/commands/npm-star.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/docs/content/commands/npm-deprecate.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/docs/content/commands/npm-audit.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/docs/content/commands/npm-search.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/docs/content/commands/npm-ls.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/docs/content/commands/npm-logout.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/docs/content/commands/npm-org.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/docs/content/commands/npm-outdated.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/docs/content/commands/npm-owner.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/docs/content/commands/npm-ping.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/docs/content/commands/npm-query.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/docs/content/commands/npm-hook.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/docs/content/configuring-npm/npm-shrinkwrap-json.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/docs/content/configuring-npm/folders.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/docs/content/configuring-npm/install.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/docs/content/configuring-npm/package-lock-json.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/docs/content/configuring-npm/npmrc.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/docs/content/configuring-npm/package-json.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/docs/content/using-npm/orgs.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/docs/content/using-npm/logging.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/docs/content/using-npm/package-spec.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/docs/content/using-npm/registry.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/docs/content/using-npm/dependency-selectors.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/docs/content/using-npm/scope.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/docs/content/using-npm/scripts.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/docs/content/using-npm/workspaces.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/docs/content/using-npm/removal.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/docs/content/using-npm/config.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/docs/content/using-npm/developers.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/node_modules/@npmcli/arborist/LICENSE.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/node_modules/@npmcli/arborist/README.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/node_modules/@npmcli/config/README.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/node_modules/@npmcli/fs/LICENSE.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/node_modules/@npmcli/installed-package-contents/README.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/node_modules/@npmcli/map-workspaces/LICENSE.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/node_modules/balanced-match/LICENSE.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/node_modules/cacache/LICENSE.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/node_modules/libnpmhook/LICENSE.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/node_modules/libnpmhook/README.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/node_modules/cssesc/README.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/node_modules/debug/node_modules/ms/license.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/node_modules/negotiator/HISTORY.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/node_modules/diff/CONTRIBUTING.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/node_modules/diff/release-notes.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/node_modules/fastest-levenshtein/LICENSE.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/node_modules/package-json-from-dist/LICENSE.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/node_modules/glob/README.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/node_modules/init-package-json/LICENSE.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/node_modules/json-parse-even-better-errors/LICENSE.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/node_modules/libnpmaccess/README.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/node_modules/libnpmdiff/README.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/node_modules/libnpmexec/README.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/node_modules/libnpmfund/README.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/node_modules/libnpmorg/README.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/node_modules/libnpmpack/README.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/node_modules/libnpmpublish/README.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/node_modules/libnpmsearch/README.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/node_modules/libnpmteam/README.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/node_modules/libnpmversion/README.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/node_modules/ms/license.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/node_modules/node-gyp/SECURITY.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/node_modules/node-gyp/CONTRIBUTING.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/node_modules/node-gyp/CHANGELOG.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/node_modules/node-gyp/README.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/node_modules/nopt/README.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/node_modules/npm-pick-manifest/LICENSE.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/node_modules/npm-profile/LICENSE.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/node_modules/npm-registry-fetch/LICENSE.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/node_modules/sprintf-js/CONTRIBUTORS.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/node_modules/pacote/README.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/node_modules/parse-conflict-json/LICENSE.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/node_modules/postcss-selector-parser/API.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/node_modules/qrcode-terminal/README.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/node_modules/safer-buffer/Porting-Buffer.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/node_modules/semver/README.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/node_modules/smart-buffer/docs/ROADMAP.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/node_modules/socks/docs/index.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/node_modules/socks/docs/migratingFromV1.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/node_modules/socks/docs/examples/index.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/node_modules/socks/docs/examples/javascript/associateExample.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/node_modules/socks/docs/examples/javascript/bindExample.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/node_modules/socks/docs/examples/javascript/connectExample.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/node_modules/socks/docs/examples/typescript/associateExample.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/node_modules/socks/docs/examples/typescript/bindExample.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/node_modules/socks/docs/examples/typescript/connectExample.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/node_modules/ssri/LICENSE.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/node_modules/tiny-relative-date/LICENSE.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/node_modules/util-deprecate/History.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/node_modules/which/README.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/node_modules/write-file-atomic/LICENSE.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/node_modules/cross-spawn/node_modules/which/README.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/node_modules/jackspeak/LICENSE.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/npm/node_modules/path-scurry/LICENSE.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/corepack/LICENSE.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/corepack/CHANGELOG.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/corepack/README.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/@qwen-code/qwen-code/node_modules/@lydell/node-pty-linux-x64/README.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/@qwen-code/qwen-code/node_modules/@lydell/node-pty/README.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/@qwen-code/qwen-code/node_modules/node-pty/deps/winpty/README.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/@qwen-code/qwen-code/node_modules/node-pty/deps/winpty/RELEASES.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/@qwen-code/qwen-code/node_modules/node-pty/README.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/@qwen-code/qwen-code/node_modules/node-addon-api/tools/README.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/@qwen-code/qwen-code/node_modules/node-addon-api/LICENSE.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/@qwen-code/qwen-code/node_modules/node-addon-api/README.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/@qwen-code/qwen-code/node_modules/tiktoken/README.md
/home/vitalij/.local/share/nvm/v18.20.8/lib/node_modules/@qwen-code/qwen-code/README.md
/home/vitalij/.local/share/nvm/v18.20.8/README.md
/home/vitalij/.local/share/nvm/v20.20.0/CHANGELOG.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/corepack/CHANGELOG.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/corepack/LICENSE.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/corepack/README.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/node_modules/libnpmexec/README.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/node_modules/tiny-relative-date/LICENSE.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/node_modules/smart-buffer/docs/ROADMAP.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/node_modules/path-scurry/LICENSE.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/node_modules/debug/node_modules/ms/license.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/node_modules/init-package-json/LICENSE.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/node_modules/ssri/LICENSE.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/node_modules/postcss-selector-parser/API.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/node_modules/libnpmhook/LICENSE.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/node_modules/libnpmhook/README.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/node_modules/package-json-from-dist/LICENSE.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/node_modules/nopt/README.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/node_modules/safer-buffer/Porting-Buffer.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/node_modules/json-parse-even-better-errors/LICENSE.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/node_modules/util-deprecate/History.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/node_modules/which/README.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/node_modules/npm-registry-fetch/LICENSE.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/node_modules/libnpmorg/README.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/node_modules/cross-spawn/node_modules/which/README.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/node_modules/negotiator/HISTORY.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/node_modules/parse-conflict-json/LICENSE.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/node_modules/cacache/LICENSE.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/node_modules/jackspeak/LICENSE.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/node_modules/glob/README.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/node_modules/libnpmaccess/README.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/node_modules/balanced-match/LICENSE.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/node_modules/libnpmpack/README.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/node_modules/sprintf-js/CONTRIBUTORS.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/node_modules/libnpmteam/README.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/node_modules/libnpmversion/README.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/node_modules/fastest-levenshtein/LICENSE.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/node_modules/@npmcli/config/README.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/node_modules/@npmcli/fs/LICENSE.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/node_modules/@npmcli/arborist/LICENSE.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/node_modules/@npmcli/arborist/README.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/node_modules/@npmcli/installed-package-contents/README.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/node_modules/@npmcli/map-workspaces/LICENSE.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/node_modules/cssesc/README.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/node_modules/ms/license.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/node_modules/node-gyp/SECURITY.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/node_modules/node-gyp/CHANGELOG.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/node_modules/node-gyp/README.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/node_modules/node-gyp/CONTRIBUTING.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/node_modules/semver/README.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/node_modules/libnpmfund/README.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/node_modules/qrcode-terminal/README.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/node_modules/socks/docs/examples/javascript/associateExample.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/node_modules/socks/docs/examples/javascript/connectExample.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/node_modules/socks/docs/examples/javascript/bindExample.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/node_modules/socks/docs/examples/typescript/associateExample.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/node_modules/socks/docs/examples/typescript/connectExample.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/node_modules/socks/docs/examples/typescript/bindExample.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/node_modules/socks/docs/examples/index.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/node_modules/socks/docs/index.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/node_modules/socks/docs/migratingFromV1.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/node_modules/libnpmpublish/README.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/node_modules/diff/release-notes.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/node_modules/diff/CONTRIBUTING.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/node_modules/npm-profile/LICENSE.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/node_modules/pacote/README.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/node_modules/libnpmdiff/README.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/node_modules/npm-pick-manifest/LICENSE.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/node_modules/libnpmsearch/README.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/node_modules/write-file-atomic/LICENSE.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/docs/content/using-npm/config.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/docs/content/using-npm/package-spec.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/docs/content/using-npm/logging.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/docs/content/using-npm/dependency-selectors.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/docs/content/using-npm/workspaces.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/docs/content/using-npm/developers.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/docs/content/using-npm/registry.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/docs/content/using-npm/scope.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/docs/content/using-npm/scripts.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/docs/content/using-npm/orgs.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/docs/content/using-npm/removal.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/docs/content/configuring-npm/install.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/docs/content/configuring-npm/package-lock-json.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/docs/content/configuring-npm/package-json.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/docs/content/configuring-npm/npmrc.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/docs/content/configuring-npm/npm-shrinkwrap-json.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/docs/content/configuring-npm/folders.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/docs/content/commands/npm-run-script.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/docs/content/commands/npm-restart.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/docs/content/commands/npm-install.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/docs/content/commands/npm-whoami.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/docs/content/commands/npm-search.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/docs/content/commands/npm-fund.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/docs/content/commands/npm-prune.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/docs/content/commands/npm-profile.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/docs/content/commands/npm-edit.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/docs/content/commands/npm-explore.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/docs/content/commands/npx.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/docs/content/commands/npm-deprecate.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/docs/content/commands/npm-audit.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/docs/content/commands/npm-start.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/docs/content/commands/npm-repo.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/docs/content/commands/npm-dedupe.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/docs/content/commands/npm-diff.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/docs/content/commands/npm-dist-tag.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/docs/content/commands/npm-view.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/docs/content/commands/npm-explain.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/docs/content/commands/npm-pkg.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/docs/content/commands/npm-rebuild.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/docs/content/commands/npm-docs.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/docs/content/commands/npm-install-test.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/docs/content/commands/npm-pack.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/docs/content/commands/npm-version.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/docs/content/commands/npm-login.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/docs/content/commands/npm-unpublish.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/docs/content/commands/npm-owner.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/docs/content/commands/npm-hook.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/docs/content/commands/npm-install-ci-test.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/docs/content/commands/npm-test.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/docs/content/commands/npm-find-dupes.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/docs/content/commands/npm-query.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/docs/content/commands/npm-uninstall.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/docs/content/commands/npm-token.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/docs/content/commands/npm.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/docs/content/commands/npm-doctor.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/docs/content/commands/npm-ping.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/docs/content/commands/npm-cache.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/docs/content/commands/npm-sbom.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/docs/content/commands/npm-completion.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/docs/content/commands/npm-help.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/docs/content/commands/npm-ls.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/docs/content/commands/npm-team.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/docs/content/commands/npm-shrinkwrap.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/docs/content/commands/npm-publish.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/docs/content/commands/npm-access.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/docs/content/commands/npm-logout.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/docs/content/commands/npm-ci.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/docs/content/commands/npm-update.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/docs/content/commands/npm-help-search.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/docs/content/commands/npm-link.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/docs/content/commands/npm-bugs.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/docs/content/commands/npm-unstar.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/docs/content/commands/npm-root.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/docs/content/commands/npm-prefix.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/docs/content/commands/npm-star.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/docs/content/commands/npm-adduser.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/docs/content/commands/npm-stop.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/docs/content/commands/npm-org.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/docs/content/commands/npm-config.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/docs/content/commands/npm-stars.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/docs/content/commands/npm-outdated.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/docs/content/commands/npm-exec.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/docs/content/commands/npm-init.md
/home/vitalij/.local/share/nvm/v20.20.0/lib/node_modules/npm/README.md
/home/vitalij/.local/share/nvm/v20.20.0/README.md
/home/vitalij/.local/share/Steam/ubuntu12_32/steam-runtime/usr/share/doc/libopusfile0/README.md
/home/vitalij/.local/share/Steam/ubuntu12_32/steam-runtime/usr/share/doc/libsdl2-2.0-0/README.md
/home/vitalij/.local/share/Steam/steamapps/common/SteamLinuxRuntime/README.md
/home/vitalij/.local/share/Steam/steamapps/common/SteamLinuxRuntime_sniper/README.md
/home/vitalij/.local/share/umu/steamrt3/README.md
