//! =======================================================================
//! АЛГОРИТМ: «УНІВЕРСАЛЬНИЙ КВАНТОВО-ХІМІЧНИЙ РЕЗОНАТОР» (Universal Chem Engine)
//! 118 хімічних елементів, 12 квантових архетипів, збалансовані тритні зв'язки {-1, 0, +1},
//! стехіометричний парсер формул та фазовий ротор на золотому перетині Φ.
//! =======================================================================

use std::collections::BTreeMap;
use std::f64::consts::PI;

/// Золотий перетин: φ = (1 + √5) / 2
pub const PHI: f64 = 1.618033988749895;

/// Кількість фундаментальних квантово-хімічних архетипів
pub const NUM_CHEM_ARCHETYPES: usize = 12;

/// Кількість хімічних елементів періодичної таблиці
pub const NUM_ELEMENTS: usize = 118;

/// Електронний блок орбіталей
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u8)]
pub enum ChemBlock {
    S = 0,
    P = 1,
    D = 2,
    F = 3,
}

/// 12 фундаментальних квантово-хімічних архетипів
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u8)]
pub enum ChemArchetype {
    AlkaliS1 = 0,
    AlkalineEarthS2 = 1,
    TransitionDBlock = 2,
    Lanthanide4F = 3,
    Actinide5F = 4,
    PostTransition = 5,
    MetalloidSemiconductor = 6,
    OrganicLifeNonmetal = 7,
    HalogenP5 = 8,
    NobleGasP6 = 9,
    SuperheavyIsland = 10,
    FrederiteResonance = 11,
}

impl ChemArchetype {
    pub fn name(&self) -> &'static str {
        match self {
            ChemArchetype::AlkaliS1 => "AlkaliS1",
            ChemArchetype::AlkalineEarthS2 => "AlkalineEarthS2",
            ChemArchetype::TransitionDBlock => "TransitionDBlock",
            ChemArchetype::Lanthanide4F => "Lanthanide4F",
            ChemArchetype::Actinide5F => "Actinide5F",
            ChemArchetype::PostTransition => "PostTransition",
            ChemArchetype::MetalloidSemiconductor => "MetalloidSemiconductor",
            ChemArchetype::OrganicLifeNonmetal => "OrganicLifeNonmetal",
            ChemArchetype::HalogenP5 => "HalogenP5",
            ChemArchetype::NobleGasP6 => "NobleGasP6",
            ChemArchetype::SuperheavyIsland => "SuperheavyIsland",
            ChemArchetype::FrederiteResonance => "FrederiteResonance",
        }
    }

    pub fn description(&self) -> &'static str {
        match self {
            ChemArchetype::AlkaliS1 => "s¹: H, Li, Na, K, Rb, Cs, Fr — моновалентні донори",
            ChemArchetype::AlkalineEarthS2 => "s²: Be, Mg, Ca, Sr, Ba, Ra — дивалентні лужноземельні",
            ChemArchetype::TransitionDBlock => "3d/4d/5d: Fe, Co, Ni, Cu, Ti, Pt, Au — спіновий резонанс та d-орбіталі",
            ChemArchetype::Lanthanide4F => "4f: La-Lu — рідкоземельний f-магнетизм та парамагнетики",
            ChemArchetype::Actinide5F => "5f: Ac-Lr — радіоактивні важкі актиноїди, ядерний розпад",
            ChemArchetype::PostTransition => "p-метали: Al, Ga, In, Sn, Pb, Bi, Po — пластичні провідники",
            ChemArchetype::MetalloidSemiconductor => "Напівпровідники: B, Si, Ge, As, Sb, Te — ковалентна зона",
            ChemArchetype::OrganicLifeNonmetal => "Органогени (sp, sp², sp³): C, N, O, P, S, Se — основа життя",
            ChemArchetype::HalogenP5 => "p⁵: F, Cl, Br, I, At, Ts — сильні окисники, акцептори електронів",
            ChemArchetype::NobleGasP6 => "p⁶: He, Ne, Ar, Kr, Xe, Rn, Og — інертний вакуумний стазис",
            ChemArchetype::SuperheavyIsland => "Z ≥ 119: Острів надважкої стабільності / релятивістські оболонки",
            ChemArchetype::FrederiteResonance => "Фредеритовий каталізатор 1.4 ТГц: метастабільні sp²/sp³ зв'язки Етерії",
        }
    }
}

/// Тип хімічного зв'язку
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum BondType {
    NonPolarCovalent, // Трит 0 (Δχ < 0.4)
    PolarCovalent,    // Трит +1 (0.4 <= Δχ <= 2.0)
    Ionic,            // Трит -1 (Δχ > 2.0)
    Metallic,         // Металічний зв'язок (між металами)
    Inert,            // Благородний газ / немає зв'язку
}

/// Паспорт хімічного елемента
#[derive(Debug, Clone, PartialEq)]
pub struct Element {
    pub z: u8,
    pub symbol: &'static str,
    pub name: &'static str,
    pub name_ru: &'static str,
    pub atomic_mass: f64,
    pub electronegativity: f64,
    pub group: u8,
    pub period: u8,
    pub block: ChemBlock,
    pub covalent_radius_pm: f32,
    pub vdw_radius_pm: f32,
    pub ionization_energy_ev: f32,
    pub electron_config: &'static str,
    pub archetype: ChemArchetype,
    pub phase_phi: f64,
}

impl Element {
    /// Чи є елемент металом
    pub fn is_metal(&self) -> bool {
        match self.archetype {
            ChemArchetype::AlkaliS1
            | ChemArchetype::AlkalineEarthS2
            | ChemArchetype::TransitionDBlock
            | ChemArchetype::Lanthanide4F
            | ChemArchetype::Actinide5F
            | ChemArchetype::PostTransition => true,
            _ => false,
        }
    }

    /// Чи є елемент типовим органогеном життя
    pub fn is_organogen(&self) -> bool {
        matches!(self.z, 1 | 6 | 7 | 8 | 15 | 16)
    }
}

/// Повна періодична таблиця 118 хімічних елементів
pub static PERIODIC_TABLE: [Element; 118] = [
    Element {
        z: 1,
        symbol: "H",
        name: "Hydrogen",
        name_ru: "Водород",
        atomic_mass: 1.008,
        electronegativity: 2.2,
        group: 1,
        period: 1,
        block: ChemBlock::S,
        covalent_radius_pm: 3e+01,
        vdw_radius_pm: 1e+02,
        ionization_energy_ev: 13.6,
        electron_config: "1s1",
        archetype: ChemArchetype::OrganicLifeNonmetal,
        phase_phi: 1.618034,
    },
    Element {
        z: 2,
        symbol: "He",
        name: "Helium",
        name_ru: "Гелий",
        atomic_mass: 4.0026,
        electronegativity: 0.0,
        group: 18,
        period: 1,
        block: ChemBlock::S,
        covalent_radius_pm: 3e+01,
        vdw_radius_pm: 1e+02,
        ionization_energy_ev: 24.6,
        electron_config: "1s2",
        archetype: ChemArchetype::NobleGasP6,
        phase_phi: 3.236068,
    },
    Element {
        z: 3,
        symbol: "Li",
        name: "Lithium",
        name_ru: "Литий",
        atomic_mass: 6.94,
        electronegativity: 0.98,
        group: 1,
        period: 2,
        block: ChemBlock::S,
        covalent_radius_pm: 1e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 5.39,
        electron_config: "[He] 2s1",
        archetype: ChemArchetype::AlkaliS1,
        phase_phi: 4.854102,
    },
    Element {
        z: 4,
        symbol: "Be",
        name: "Beryllium",
        name_ru: "Бериллий",
        atomic_mass: 9.01218,
        electronegativity: 1.6,
        group: 2,
        period: 2,
        block: ChemBlock::S,
        covalent_radius_pm: 1e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 9.32,
        electron_config: "[He] 2s2",
        archetype: ChemArchetype::AlkalineEarthS2,
        phase_phi: 0.18895065,
    },
    Element {
        z: 5,
        symbol: "B",
        name: "Boron",
        name_ru: "Бор",
        atomic_mass: 10.81,
        electronegativity: 2.0,
        group: 13,
        period: 2,
        block: ChemBlock::P,
        covalent_radius_pm: 8e+01,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 8.3,
        electron_config: "[He] 2s2 2p1",
        archetype: ChemArchetype::MetalloidSemiconductor,
        phase_phi: 1.8069846,
    },
    Element {
        z: 6,
        symbol: "C",
        name: "Carbon",
        name_ru: "Углерод",
        atomic_mass: 12.011,
        electronegativity: 2.5,
        group: 14,
        period: 2,
        block: ChemBlock::P,
        covalent_radius_pm: 8e+01,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 11.3,
        electron_config: "[He] 2s2 2p2",
        archetype: ChemArchetype::OrganicLifeNonmetal,
        phase_phi: 3.4250186,
    },
    Element {
        z: 7,
        symbol: "N",
        name: "Nitrogen",
        name_ru: "Азот",
        atomic_mass: 14.007,
        electronegativity: 3.0,
        group: 15,
        period: 2,
        block: ChemBlock::P,
        covalent_radius_pm: 7e+01,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 14.5,
        electron_config: "[He] 2s2 2p3",
        archetype: ChemArchetype::OrganicLifeNonmetal,
        phase_phi: 5.0430526,
    },
    Element {
        z: 8,
        symbol: "O",
        name: "Oxygen",
        name_ru: "Кислород",
        atomic_mass: 15.999,
        electronegativity: 3.4,
        group: 16,
        period: 2,
        block: ChemBlock::P,
        covalent_radius_pm: 7e+01,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 13.6,
        electron_config: "[He] 2s2 2p4",
        archetype: ChemArchetype::OrganicLifeNonmetal,
        phase_phi: 0.3779013,
    },
    Element {
        z: 9,
        symbol: "F",
        name: "Fluorine",
        name_ru: "Фтор",
        atomic_mass: 18.9984,
        electronegativity: 4.0,
        group: 17,
        period: 2,
        block: ChemBlock::P,
        covalent_radius_pm: 6e+01,
        vdw_radius_pm: 1e+02,
        ionization_energy_ev: 17.4,
        electron_config: "[He] 2s2 2p5",
        archetype: ChemArchetype::HalogenP5,
        phase_phi: 1.9959353,
    },
    Element {
        z: 10,
        symbol: "Ne",
        name: "Neon",
        name_ru: "Неон",
        atomic_mass: 20.1797,
        electronegativity: 0.0,
        group: 18,
        period: 2,
        block: ChemBlock::P,
        covalent_radius_pm: 6e+01,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 21.6,
        electron_config: "[He] 2s2 2p6",
        archetype: ChemArchetype::NobleGasP6,
        phase_phi: 3.6139693,
    },
    Element {
        z: 11,
        symbol: "Na",
        name: "Sodium",
        name_ru: "Натрий",
        atomic_mass: 22.9898,
        electronegativity: 0.93,
        group: 1,
        period: 3,
        block: ChemBlock::S,
        covalent_radius_pm: 2e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 5.14,
        electron_config: "[Ne] 3s1",
        archetype: ChemArchetype::AlkaliS1,
        phase_phi: 5.2320033,
    },
    Element {
        z: 12,
        symbol: "Mg",
        name: "Magnesium",
        name_ru: "Магний",
        atomic_mass: 24.305,
        electronegativity: 1.3,
        group: 2,
        period: 3,
        block: ChemBlock::S,
        covalent_radius_pm: 1e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 7.65,
        electron_config: "[Ne] 3s2",
        archetype: ChemArchetype::AlkalineEarthS2,
        phase_phi: 0.56685194,
    },
    Element {
        z: 13,
        symbol: "Al",
        name: "Aluminium",
        name_ru: "Алюминий",
        atomic_mass: 26.9815,
        electronegativity: 1.6,
        group: 13,
        period: 3,
        block: ChemBlock::P,
        covalent_radius_pm: 1e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 5.99,
        electron_config: "[Ne] 3s2 3p1",
        archetype: ChemArchetype::PostTransition,
        phase_phi: 2.1848859,
    },
    Element {
        z: 14,
        symbol: "Si",
        name: "Silicon",
        name_ru: "Кремний",
        atomic_mass: 28.085,
        electronegativity: 1.9,
        group: 14,
        period: 3,
        block: ChemBlock::P,
        covalent_radius_pm: 1e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 8.15,
        electron_config: "[Ne] 3s2 3p2",
        archetype: ChemArchetype::MetalloidSemiconductor,
        phase_phi: 3.8029199,
    },
    Element {
        z: 15,
        symbol: "P",
        name: "Phosphorus",
        name_ru: "Фосфор",
        atomic_mass: 30.9738,
        electronegativity: 2.2,
        group: 15,
        period: 3,
        block: ChemBlock::P,
        covalent_radius_pm: 1e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 10.5,
        electron_config: "[Ne] 3s2 3p3",
        archetype: ChemArchetype::OrganicLifeNonmetal,
        phase_phi: 5.4209539,
    },
    Element {
        z: 16,
        symbol: "S",
        name: "Sulfur",
        name_ru: "Сера",
        atomic_mass: 32.06,
        electronegativity: 2.6,
        group: 16,
        period: 3,
        block: ChemBlock::P,
        covalent_radius_pm: 1e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 10.4,
        electron_config: "[Ne] 3s2 3p4",
        archetype: ChemArchetype::OrganicLifeNonmetal,
        phase_phi: 0.75580259,
    },
    Element {
        z: 17,
        symbol: "Cl",
        name: "Chlorine",
        name_ru: "Хлор",
        atomic_mass: 35.45,
        electronegativity: 3.2,
        group: 17,
        period: 3,
        block: ChemBlock::P,
        covalent_radius_pm: 1e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 13.0,
        electron_config: "[Ne] 3s2 3p5",
        archetype: ChemArchetype::HalogenP5,
        phase_phi: 2.3738366,
    },
    Element {
        z: 18,
        symbol: "Ar",
        name: "Argon",
        name_ru: "Аргон",
        atomic_mass: 39.948,
        electronegativity: 0.0,
        group: 18,
        period: 3,
        block: ChemBlock::P,
        covalent_radius_pm: 1e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 15.8,
        electron_config: "[Ne] 3s2 3p6",
        archetype: ChemArchetype::NobleGasP6,
        phase_phi: 3.9918706,
    },
    Element {
        z: 19,
        symbol: "K",
        name: "Potassium",
        name_ru: "Калий",
        atomic_mass: 39.0983,
        electronegativity: 0.82,
        group: 1,
        period: 4,
        block: ChemBlock::S,
        covalent_radius_pm: 2e+02,
        vdw_radius_pm: 3e+02,
        ionization_energy_ev: 4.34,
        electron_config: "[Ar] 4s1",
        archetype: ChemArchetype::AlkaliS1,
        phase_phi: 5.6099046,
    },
    Element {
        z: 20,
        symbol: "Ca",
        name: "Calcium",
        name_ru: "Кальций",
        atomic_mass: 40.078,
        electronegativity: 1.0,
        group: 2,
        period: 4,
        block: ChemBlock::S,
        covalent_radius_pm: 2e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 6.11,
        electron_config: "[Ar] 4s2",
        archetype: ChemArchetype::AlkalineEarthS2,
        phase_phi: 0.94475324,
    },
    Element {
        z: 21,
        symbol: "Sc",
        name: "Scandium",
        name_ru: "Скандий",
        atomic_mass: 44.9559,
        electronegativity: 1.4,
        group: 3,
        period: 4,
        block: ChemBlock::D,
        covalent_radius_pm: 2e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 6.56,
        electron_config: "[Ar] 3d1 4s2",
        archetype: ChemArchetype::TransitionDBlock,
        phase_phi: 2.5627872,
    },
    Element {
        z: 22,
        symbol: "Ti",
        name: "Titanium",
        name_ru: "Титан",
        atomic_mass: 47.867,
        electronegativity: 1.5,
        group: 4,
        period: 4,
        block: ChemBlock::D,
        covalent_radius_pm: 2e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 6.83,
        electron_config: "[Ar] 3d2 4s2",
        archetype: ChemArchetype::TransitionDBlock,
        phase_phi: 4.1808212,
    },
    Element {
        z: 23,
        symbol: "V",
        name: "Vanadium",
        name_ru: "Ванадий",
        atomic_mass: 50.9415,
        electronegativity: 1.6,
        group: 5,
        period: 4,
        block: ChemBlock::D,
        covalent_radius_pm: 2e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 6.75,
        electron_config: "[Ar] 3d3 4s2",
        archetype: ChemArchetype::TransitionDBlock,
        phase_phi: 5.7988552,
    },
    Element {
        z: 24,
        symbol: "Cr",
        name: "Chromium",
        name_ru: "Хром",
        atomic_mass: 51.9961,
        electronegativity: 1.7,
        group: 6,
        period: 4,
        block: ChemBlock::D,
        covalent_radius_pm: 1e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 6.77,
        electron_config: "[Ar] 3d5 4s1",
        archetype: ChemArchetype::TransitionDBlock,
        phase_phi: 1.1337039,
    },
    Element {
        z: 25,
        symbol: "Mn",
        name: "Manganese",
        name_ru: "Марганец",
        atomic_mass: 54.938,
        electronegativity: 1.6,
        group: 7,
        period: 4,
        block: ChemBlock::D,
        covalent_radius_pm: 1e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 7.43,
        electron_config: "[Ar] 3d5 4s2",
        archetype: ChemArchetype::TransitionDBlock,
        phase_phi: 2.7517379,
    },
    Element {
        z: 26,
        symbol: "Fe",
        name: "Iron",
        name_ru: "Железо",
        atomic_mass: 55.845,
        electronegativity: 1.8,
        group: 8,
        period: 4,
        block: ChemBlock::D,
        covalent_radius_pm: 1e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 7.9,
        electron_config: "[Ar] 3d6 4s2",
        archetype: ChemArchetype::TransitionDBlock,
        phase_phi: 4.3697719,
    },
    Element {
        z: 27,
        symbol: "Co",
        name: "Cobalt",
        name_ru: "Кобальт",
        atomic_mass: 58.9332,
        electronegativity: 1.9,
        group: 9,
        period: 4,
        block: ChemBlock::D,
        covalent_radius_pm: 1e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 7.88,
        electron_config: "[Ar] 3d7 4s2",
        archetype: ChemArchetype::TransitionDBlock,
        phase_phi: 5.9878059,
    },
    Element {
        z: 28,
        symbol: "Ni",
        name: "Nickel",
        name_ru: "Никель",
        atomic_mass: 58.6934,
        electronegativity: 1.9,
        group: 10,
        period: 4,
        block: ChemBlock::D,
        covalent_radius_pm: 1e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 7.64,
        electron_config: "[Ar] 3d8 4s2",
        archetype: ChemArchetype::TransitionDBlock,
        phase_phi: 1.3226545,
    },
    Element {
        z: 29,
        symbol: "Cu",
        name: "Copper",
        name_ru: "Медь",
        atomic_mass: 63.546,
        electronegativity: 1.9,
        group: 11,
        period: 4,
        block: ChemBlock::D,
        covalent_radius_pm: 1e+02,
        vdw_radius_pm: 1e+02,
        ionization_energy_ev: 7.73,
        electron_config: "[Ar] 3d10 4s1",
        archetype: ChemArchetype::TransitionDBlock,
        phase_phi: 2.9406885,
    },
    Element {
        z: 30,
        symbol: "Zn",
        name: "Zinc",
        name_ru: "Цинк",
        atomic_mass: 65.38,
        electronegativity: 1.6,
        group: 12,
        period: 4,
        block: ChemBlock::D,
        covalent_radius_pm: 1e+02,
        vdw_radius_pm: 1e+02,
        ionization_energy_ev: 9.39,
        electron_config: "[Ar] 3d10 4s2",
        archetype: ChemArchetype::TransitionDBlock,
        phase_phi: 4.5587225,
    },
    Element {
        z: 31,
        symbol: "Ga",
        name: "Gallium",
        name_ru: "Галлий",
        atomic_mass: 69.723,
        electronegativity: 1.8,
        group: 13,
        period: 4,
        block: ChemBlock::P,
        covalent_radius_pm: 1e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 6.0,
        electron_config: "[Ar] 3d10 4s2 4p1",
        archetype: ChemArchetype::PostTransition,
        phase_phi: 6.1767565,
    },
    Element {
        z: 32,
        symbol: "Ge",
        name: "Germanium",
        name_ru: "Германий",
        atomic_mass: 72.63,
        electronegativity: 2.0,
        group: 14,
        period: 4,
        block: ChemBlock::P,
        covalent_radius_pm: 1e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 7.9,
        electron_config: "[Ar] 3d10 4s2 4p2",
        archetype: ChemArchetype::MetalloidSemiconductor,
        phase_phi: 1.5116052,
    },
    Element {
        z: 33,
        symbol: "As",
        name: "Arsenic",
        name_ru: "Мышьяк",
        atomic_mass: 74.9216,
        electronegativity: 2.2,
        group: 15,
        period: 4,
        block: ChemBlock::P,
        covalent_radius_pm: 1e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 9.79,
        electron_config: "[Ar] 3d10 4s2 4p3",
        archetype: ChemArchetype::MetalloidSemiconductor,
        phase_phi: 3.1296392,
    },
    Element {
        z: 34,
        symbol: "Se",
        name: "Selenium",
        name_ru: "Селен",
        atomic_mass: 78.971,
        electronegativity: 2.5,
        group: 16,
        period: 4,
        block: ChemBlock::P,
        covalent_radius_pm: 1e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 9.75,
        electron_config: "[Ar] 3d10 4s2 4p4",
        archetype: ChemArchetype::OrganicLifeNonmetal,
        phase_phi: 4.7476732,
    },
    Element {
        z: 35,
        symbol: "Br",
        name: "Bromine",
        name_ru: "Бром",
        atomic_mass: 79.904,
        electronegativity: 3.0,
        group: 17,
        period: 4,
        block: ChemBlock::P,
        covalent_radius_pm: 1e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 11.8,
        electron_config: "[Ar] 3d10 4s2 4p5",
        archetype: ChemArchetype::HalogenP5,
        phase_phi: 0.082521842,
    },
    Element {
        z: 36,
        symbol: "Kr",
        name: "Krypton",
        name_ru: "Криптон",
        atomic_mass: 83.798,
        electronegativity: 3.0,
        group: 18,
        period: 4,
        block: ChemBlock::P,
        covalent_radius_pm: 1e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 14.0,
        electron_config: "[Ar] 3d10 4s2 4p6",
        archetype: ChemArchetype::NobleGasP6,
        phase_phi: 1.7005558,
    },
    Element {
        z: 37,
        symbol: "Rb",
        name: "Rubidium",
        name_ru: "Рубидий",
        atomic_mass: 85.4678,
        electronegativity: 0.82,
        group: 1,
        period: 5,
        block: ChemBlock::S,
        covalent_radius_pm: 2e+02,
        vdw_radius_pm: 3e+02,
        ionization_energy_ev: 4.18,
        electron_config: "[Kr] 5s1",
        archetype: ChemArchetype::AlkaliS1,
        phase_phi: 3.3185898,
    },
    Element {
        z: 38,
        symbol: "Sr",
        name: "Strontium",
        name_ru: "Стронций",
        atomic_mass: 87.62,
        electronegativity: 0.95,
        group: 2,
        period: 5,
        block: ChemBlock::S,
        covalent_radius_pm: 2e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 5.7,
        electron_config: "[Kr] 5s2",
        archetype: ChemArchetype::AlkalineEarthS2,
        phase_phi: 4.9366238,
    },
    Element {
        z: 39,
        symbol: "Y",
        name: "Yttrium",
        name_ru: "Иттрий",
        atomic_mass: 88.9058,
        electronegativity: 1.2,
        group: 3,
        period: 5,
        block: ChemBlock::D,
        covalent_radius_pm: 2e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 6.22,
        electron_config: "[Kr] 4d1 5s2",
        archetype: ChemArchetype::TransitionDBlock,
        phase_phi: 0.27147249,
    },
    Element {
        z: 40,
        symbol: "Zr",
        name: "Zirconium",
        name_ru: "Цирконий",
        atomic_mass: 91.224,
        electronegativity: 1.3,
        group: 4,
        period: 5,
        block: ChemBlock::D,
        covalent_radius_pm: 2e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 6.63,
        electron_config: "[Kr] 4d2 5s2",
        archetype: ChemArchetype::TransitionDBlock,
        phase_phi: 1.8895065,
    },
    Element {
        z: 41,
        symbol: "Nb",
        name: "Niobium",
        name_ru: "Ниобий",
        atomic_mass: 92.9064,
        electronegativity: 1.6,
        group: 5,
        period: 5,
        block: ChemBlock::D,
        covalent_radius_pm: 2e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 6.76,
        electron_config: "[Kr] 4d4 5s1",
        archetype: ChemArchetype::TransitionDBlock,
        phase_phi: 3.5075405,
    },
    Element {
        z: 42,
        symbol: "Mo",
        name: "Molybdenum",
        name_ru: "Молибден",
        atomic_mass: 95.95,
        electronegativity: 2.2,
        group: 6,
        period: 5,
        block: ChemBlock::D,
        covalent_radius_pm: 2e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 7.09,
        electron_config: "[Kr] 4d5 5s1",
        archetype: ChemArchetype::TransitionDBlock,
        phase_phi: 5.1255745,
    },
    Element {
        z: 43,
        symbol: "Tc",
        name: "Technetium",
        name_ru: "Технеций",
        atomic_mass: 98.0,
        electronegativity: 1.9,
        group: 7,
        period: 5,
        block: ChemBlock::D,
        covalent_radius_pm: 1e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 7.28,
        electron_config: "[Kr] 4d5 5s2",
        archetype: ChemArchetype::TransitionDBlock,
        phase_phi: 0.46042314,
    },
    Element {
        z: 44,
        symbol: "Ru",
        name: "Ruthenium",
        name_ru: "Рутений",
        atomic_mass: 101.07,
        electronegativity: 2.2,
        group: 8,
        period: 5,
        block: ChemBlock::D,
        covalent_radius_pm: 1e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 7.36,
        electron_config: "[Kr] 4d7 5s1",
        archetype: ChemArchetype::TransitionDBlock,
        phase_phi: 2.0784571,
    },
    Element {
        z: 45,
        symbol: "Rh",
        name: "Rhodium",
        name_ru: "Родий",
        atomic_mass: 102.906,
        electronegativity: 2.3,
        group: 9,
        period: 5,
        block: ChemBlock::D,
        covalent_radius_pm: 1e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 7.46,
        electron_config: "[Kr] 4d8 5s1",
        archetype: ChemArchetype::TransitionDBlock,
        phase_phi: 3.6964911,
    },
    Element {
        z: 46,
        symbol: "Pd",
        name: "Palladium",
        name_ru: "Палладий",
        atomic_mass: 106.42,
        electronegativity: 2.2,
        group: 10,
        period: 5,
        block: ChemBlock::D,
        covalent_radius_pm: 1e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 8.34,
        electron_config: "[Kr] 4d10",
        archetype: ChemArchetype::TransitionDBlock,
        phase_phi: 5.3145251,
    },
    Element {
        z: 47,
        symbol: "Ag",
        name: "Silver",
        name_ru: "Серебро",
        atomic_mass: 107.868,
        electronegativity: 1.9,
        group: 11,
        period: 5,
        block: ChemBlock::D,
        covalent_radius_pm: 1e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 7.58,
        electron_config: "[Kr] 4d10 5s1",
        archetype: ChemArchetype::TransitionDBlock,
        phase_phi: 0.64937379,
    },
    Element {
        z: 48,
        symbol: "Cd",
        name: "Cadmium",
        name_ru: "Кадмий",
        atomic_mass: 112.414,
        electronegativity: 1.7,
        group: 12,
        period: 5,
        block: ChemBlock::D,
        covalent_radius_pm: 1e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 8.99,
        electron_config: "[Kr] 4d10 5s2",
        archetype: ChemArchetype::TransitionDBlock,
        phase_phi: 2.2674078,
    },
    Element {
        z: 49,
        symbol: "In",
        name: "Indium",
        name_ru: "Индий",
        atomic_mass: 114.818,
        electronegativity: 1.8,
        group: 13,
        period: 5,
        block: ChemBlock::P,
        covalent_radius_pm: 1e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 5.79,
        electron_config: "[Kr] 4d10 5s2 5p1",
        archetype: ChemArchetype::PostTransition,
        phase_phi: 3.8854418,
    },
    Element {
        z: 50,
        symbol: "Sn",
        name: "Tin",
        name_ru: "Олово",
        atomic_mass: 118.71,
        electronegativity: 2.0,
        group: 14,
        period: 5,
        block: ChemBlock::P,
        covalent_radius_pm: 1e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 7.34,
        electron_config: "[Kr] 4d10 5s2 5p2",
        archetype: ChemArchetype::PostTransition,
        phase_phi: 5.5034758,
    },
    Element {
        z: 51,
        symbol: "Sb",
        name: "Antimony",
        name_ru: "Сурьма",
        atomic_mass: 121.76,
        electronegativity: 2.0,
        group: 15,
        period: 5,
        block: ChemBlock::P,
        covalent_radius_pm: 1e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 8.61,
        electron_config: "[Kr] 4d10 5s2 5p3",
        archetype: ChemArchetype::MetalloidSemiconductor,
        phase_phi: 0.83832443,
    },
    Element {
        z: 52,
        symbol: "Te",
        name: "Tellurium",
        name_ru: "Теллур",
        atomic_mass: 127.6,
        electronegativity: 2.1,
        group: 16,
        period: 5,
        block: ChemBlock::P,
        covalent_radius_pm: 1e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 9.01,
        electron_config: "[Kr] 4d10 5s2 5p4",
        archetype: ChemArchetype::MetalloidSemiconductor,
        phase_phi: 2.4563584,
    },
    Element {
        z: 53,
        symbol: "I",
        name: "Iodine",
        name_ru: "Иод",
        atomic_mass: 126.904,
        electronegativity: 2.7,
        group: 17,
        period: 5,
        block: ChemBlock::P,
        covalent_radius_pm: 1e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 10.5,
        electron_config: "[Kr] 4d10 5s2 5p5",
        archetype: ChemArchetype::HalogenP5,
        phase_phi: 4.0743924,
    },
    Element {
        z: 54,
        symbol: "Xe",
        name: "Xenon",
        name_ru: "Ксенон",
        atomic_mass: 131.293,
        electronegativity: 2.6,
        group: 18,
        period: 5,
        block: ChemBlock::P,
        covalent_radius_pm: 1e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 12.1,
        electron_config: "[Kr] 4d10 5s2 5p6",
        archetype: ChemArchetype::NobleGasP6,
        phase_phi: 5.6924264,
    },
    Element {
        z: 55,
        symbol: "Cs",
        name: "Caesium",
        name_ru: "Цезий",
        atomic_mass: 132.905,
        electronegativity: 0.79,
        group: 1,
        period: 6,
        block: ChemBlock::S,
        covalent_radius_pm: 2e+02,
        vdw_radius_pm: 3e+02,
        ionization_energy_ev: 3.89,
        electron_config: "[Xe] 6s1",
        archetype: ChemArchetype::AlkaliS1,
        phase_phi: 1.0272751,
    },
    Element {
        z: 56,
        symbol: "Ba",
        name: "Barium",
        name_ru: "Барий",
        atomic_mass: 137.327,
        electronegativity: 0.89,
        group: 2,
        period: 6,
        block: ChemBlock::S,
        covalent_radius_pm: 2e+02,
        vdw_radius_pm: 3e+02,
        ionization_energy_ev: 5.21,
        electron_config: "[Xe] 6s2",
        archetype: ChemArchetype::AlkalineEarthS2,
        phase_phi: 2.6453091,
    },
    Element {
        z: 57,
        symbol: "La",
        name: "Lanthanum",
        name_ru: "Лантан",
        atomic_mass: 138.905,
        electronegativity: 1.1,
        group: 3,
        period: 6,
        block: ChemBlock::F,
        covalent_radius_pm: 2e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 5.58,
        electron_config: "[Xe] 5d1 6s2",
        archetype: ChemArchetype::Lanthanide4F,
        phase_phi: 4.2633431,
    },
    Element {
        z: 58,
        symbol: "Ce",
        name: "Cerium",
        name_ru: "Церий",
        atomic_mass: 140.116,
        electronegativity: 1.1,
        group: 3,
        period: 6,
        block: ChemBlock::F,
        covalent_radius_pm: 2e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 5.54,
        electron_config: "[Xe] 4f1 5d1 6s2",
        archetype: ChemArchetype::Lanthanide4F,
        phase_phi: 5.881377,
    },
    Element {
        z: 59,
        symbol: "Pr",
        name: "Praseodymium",
        name_ru: "Празеодим",
        atomic_mass: 140.908,
        electronegativity: 1.1,
        group: 3,
        period: 6,
        block: ChemBlock::F,
        covalent_radius_pm: 2e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 5.47,
        electron_config: "[Xe] 4f3 6s2",
        archetype: ChemArchetype::Lanthanide4F,
        phase_phi: 1.2162257,
    },
    Element {
        z: 60,
        symbol: "Nd",
        name: "Neodymium",
        name_ru: "Неодим",
        atomic_mass: 144.242,
        electronegativity: 1.1,
        group: 3,
        period: 6,
        block: ChemBlock::F,
        covalent_radius_pm: 2e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 5.53,
        electron_config: "[Xe] 4f4 6s2",
        archetype: ChemArchetype::Lanthanide4F,
        phase_phi: 2.8342597,
    },
    Element {
        z: 61,
        symbol: "Pm",
        name: "Promethium",
        name_ru: "Прометий",
        atomic_mass: 145.0,
        electronegativity: 1.1,
        group: 3,
        period: 6,
        block: ChemBlock::F,
        covalent_radius_pm: 2e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 5.58,
        electron_config: "[Xe] 4f5 6s2",
        archetype: ChemArchetype::Lanthanide4F,
        phase_phi: 4.4522937,
    },
    Element {
        z: 62,
        symbol: "Sm",
        name: "Samarium",
        name_ru: "Самарий",
        atomic_mass: 150.36,
        electronegativity: 1.2,
        group: 3,
        period: 6,
        block: ChemBlock::F,
        covalent_radius_pm: 2e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 5.64,
        electron_config: "[Xe] 4f6 6s2",
        archetype: ChemArchetype::Lanthanide4F,
        phase_phi: 6.0703277,
    },
    Element {
        z: 63,
        symbol: "Eu",
        name: "Europium",
        name_ru: "Европий",
        atomic_mass: 151.964,
        electronegativity: 1.2,
        group: 3,
        period: 6,
        block: ChemBlock::F,
        covalent_radius_pm: 2e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 5.67,
        electron_config: "[Xe] 4f7 6s2",
        archetype: ChemArchetype::Lanthanide4F,
        phase_phi: 1.4051764,
    },
    Element {
        z: 64,
        symbol: "Gd",
        name: "Gadolinium",
        name_ru: "Гадолиний",
        atomic_mass: 157.25,
        electronegativity: 1.2,
        group: 3,
        period: 6,
        block: ChemBlock::F,
        covalent_radius_pm: 2e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 6.15,
        electron_config: "[Xe] 4f7 5d1 6s2",
        archetype: ChemArchetype::Lanthanide4F,
        phase_phi: 3.0232104,
    },
    Element {
        z: 65,
        symbol: "Tb",
        name: "Terbium",
        name_ru: "Тербий",
        atomic_mass: 158.925,
        electronegativity: 1.2,
        group: 3,
        period: 6,
        block: ChemBlock::F,
        covalent_radius_pm: 2e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 5.86,
        electron_config: "[Xe] 4f9 6s2",
        archetype: ChemArchetype::Lanthanide4F,
        phase_phi: 4.6412444,
    },
    Element {
        z: 66,
        symbol: "Dy",
        name: "Dysprosium",
        name_ru: "Диспрозий",
        atomic_mass: 162.5,
        electronegativity: 1.2,
        group: 3,
        period: 6,
        block: ChemBlock::F,
        covalent_radius_pm: 2e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 5.94,
        electron_config: "[Xe] 4f10 6s2",
        archetype: ChemArchetype::Lanthanide4F,
        phase_phi: 6.2592783,
    },
    Element {
        z: 67,
        symbol: "Ho",
        name: "Holmium",
        name_ru: "Гольмий",
        atomic_mass: 164.93,
        electronegativity: 1.2,
        group: 3,
        period: 6,
        block: ChemBlock::F,
        covalent_radius_pm: 2e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 6.02,
        electron_config: "[Xe] 4f11 6s2",
        archetype: ChemArchetype::Lanthanide4F,
        phase_phi: 1.594127,
    },
    Element {
        z: 68,
        symbol: "Er",
        name: "Erbium",
        name_ru: "Эрбий",
        atomic_mass: 167.259,
        electronegativity: 1.2,
        group: 3,
        period: 6,
        block: ChemBlock::F,
        covalent_radius_pm: 2e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 6.11,
        electron_config: "[Xe] 4f12 6s2",
        archetype: ChemArchetype::Lanthanide4F,
        phase_phi: 3.212161,
    },
    Element {
        z: 69,
        symbol: "Tm",
        name: "Thulium",
        name_ru: "Тулий",
        atomic_mass: 168.934,
        electronegativity: 1.2,
        group: 3,
        period: 6,
        block: ChemBlock::F,
        covalent_radius_pm: 2e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 6.18,
        electron_config: "[Xe] 4f13 6s2",
        archetype: ChemArchetype::Lanthanide4F,
        phase_phi: 4.830195,
    },
    Element {
        z: 70,
        symbol: "Yb",
        name: "Ytterbium",
        name_ru: "Иттербий",
        atomic_mass: 173.045,
        electronegativity: 1.1,
        group: 3,
        period: 6,
        block: ChemBlock::F,
        covalent_radius_pm: 2e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 6.25,
        electron_config: "[Xe] 4f14 6s2",
        archetype: ChemArchetype::Lanthanide4F,
        phase_phi: 0.16504368,
    },
    Element {
        z: 71,
        symbol: "Lu",
        name: "Lutetium",
        name_ru: "Лютеций",
        atomic_mass: 174.967,
        electronegativity: 1.3,
        group: 3,
        period: 6,
        block: ChemBlock::D,
        covalent_radius_pm: 2e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 5.43,
        electron_config: "[Xe] 4f14 5d1 6s2",
        archetype: ChemArchetype::Lanthanide4F,
        phase_phi: 1.7830777,
    },
    Element {
        z: 72,
        symbol: "Hf",
        name: "Hafnium",
        name_ru: "Гафний",
        atomic_mass: 178.49,
        electronegativity: 1.3,
        group: 4,
        period: 6,
        block: ChemBlock::D,
        covalent_radius_pm: 2e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 6.83,
        electron_config: "[Xe] 4f14 5d2 6s2",
        archetype: ChemArchetype::TransitionDBlock,
        phase_phi: 3.4011117,
    },
    Element {
        z: 73,
        symbol: "Ta",
        name: "Tantalum",
        name_ru: "Тантал",
        atomic_mass: 180.948,
        electronegativity: 1.5,
        group: 5,
        period: 6,
        block: ChemBlock::D,
        covalent_radius_pm: 2e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 7.55,
        electron_config: "[Xe] 4f14 5d3 6s2",
        archetype: ChemArchetype::TransitionDBlock,
        phase_phi: 5.0191456,
    },
    Element {
        z: 74,
        symbol: "W",
        name: "Tungsten",
        name_ru: "Вольфрам",
        atomic_mass: 183.84,
        electronegativity: 2.4,
        group: 6,
        period: 6,
        block: ChemBlock::D,
        covalent_radius_pm: 2e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 7.86,
        electron_config: "[Xe] 4f14 5d4 6s2",
        archetype: ChemArchetype::TransitionDBlock,
        phase_phi: 0.35399433,
    },
    Element {
        z: 75,
        symbol: "Re",
        name: "Rhenium",
        name_ru: "Рений",
        atomic_mass: 186.207,
        electronegativity: 1.9,
        group: 7,
        period: 6,
        block: ChemBlock::D,
        covalent_radius_pm: 2e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 7.83,
        electron_config: "[Xe] 4f14 5d5 6s2",
        archetype: ChemArchetype::TransitionDBlock,
        phase_phi: 1.9720283,
    },
    Element {
        z: 76,
        symbol: "Os",
        name: "Osmium",
        name_ru: "Осмий",
        atomic_mass: 190.23,
        electronegativity: 2.2,
        group: 8,
        period: 6,
        block: ChemBlock::D,
        covalent_radius_pm: 1e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 8.44,
        electron_config: "[Xe] 4f14 5d6 6s2",
        archetype: ChemArchetype::TransitionDBlock,
        phase_phi: 3.5900623,
    },
    Element {
        z: 77,
        symbol: "Ir",
        name: "Iridium",
        name_ru: "Иридий",
        atomic_mass: 192.217,
        electronegativity: 2.2,
        group: 9,
        period: 6,
        block: ChemBlock::D,
        covalent_radius_pm: 1e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 8.97,
        electron_config: "[Xe] 4f14 5d7 6s2",
        archetype: ChemArchetype::TransitionDBlock,
        phase_phi: 5.2080963,
    },
    Element {
        z: 78,
        symbol: "Pt",
        name: "Platinum",
        name_ru: "Платина",
        atomic_mass: 195.084,
        electronegativity: 2.3,
        group: 10,
        period: 6,
        block: ChemBlock::D,
        covalent_radius_pm: 1e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 8.96,
        electron_config: "[Xe] 4f14 5d9 6s1",
        archetype: ChemArchetype::TransitionDBlock,
        phase_phi: 0.54294498,
    },
    Element {
        z: 79,
        symbol: "Au",
        name: "Gold",
        name_ru: "Золото",
        atomic_mass: 196.967,
        electronegativity: 2.5,
        group: 11,
        period: 6,
        block: ChemBlock::D,
        covalent_radius_pm: 1e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 9.23,
        electron_config: "[Xe] 4f14 5d10 6s1",
        archetype: ChemArchetype::TransitionDBlock,
        phase_phi: 2.160979,
    },
    Element {
        z: 80,
        symbol: "Hg",
        name: "Mercury",
        name_ru: "Ртуть",
        atomic_mass: 200.592,
        electronegativity: 2.0,
        group: 12,
        period: 6,
        block: ChemBlock::D,
        covalent_radius_pm: 1e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 10.4,
        electron_config: "[Xe] 4f14 5d10 6s2",
        archetype: ChemArchetype::TransitionDBlock,
        phase_phi: 3.779013,
    },
    Element {
        z: 81,
        symbol: "Tl",
        name: "Thallium",
        name_ru: "Таллий",
        atomic_mass: 204.38,
        electronegativity: 1.6,
        group: 13,
        period: 6,
        block: ChemBlock::P,
        covalent_radius_pm: 1e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 6.11,
        electron_config: "[Xe] 4f14 5d10 6s2 6p1",
        archetype: ChemArchetype::PostTransition,
        phase_phi: 5.3970469,
    },
    Element {
        z: 82,
        symbol: "Pb",
        name: "Lead",
        name_ru: "Свинец",
        atomic_mass: 207.2,
        electronegativity: 2.3,
        group: 14,
        period: 6,
        block: ChemBlock::P,
        covalent_radius_pm: 1e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 7.42,
        electron_config: "[Xe] 4f14 5d10 6s2 6p2",
        archetype: ChemArchetype::PostTransition,
        phase_phi: 0.73189563,
    },
    Element {
        z: 83,
        symbol: "Bi",
        name: "Bismuth",
        name_ru: "Висмут",
        atomic_mass: 208.98,
        electronegativity: 2.0,
        group: 15,
        period: 6,
        block: ChemBlock::P,
        covalent_radius_pm: 1e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 7.29,
        electron_config: "[Xe] 4f14 5d10 6s2 6p3",
        archetype: ChemArchetype::PostTransition,
        phase_phi: 2.3499296,
    },
    Element {
        z: 84,
        symbol: "Po",
        name: "Polonium",
        name_ru: "Полоний",
        atomic_mass: 209.0,
        electronegativity: 2.0,
        group: 16,
        period: 6,
        block: ChemBlock::P,
        covalent_radius_pm: 1e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 8.42,
        electron_config: "[Xe] 4f14 5d10 6s2 6p4",
        archetype: ChemArchetype::PostTransition,
        phase_phi: 3.9679636,
    },
    Element {
        z: 85,
        symbol: "At",
        name: "Astatine",
        name_ru: "Астат",
        atomic_mass: 210.0,
        electronegativity: 2.2,
        group: 17,
        period: 6,
        block: ChemBlock::P,
        covalent_radius_pm: 2e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 9.32,
        electron_config: "[Xe] 4f14 5d10 6s2 6p5",
        archetype: ChemArchetype::HalogenP5,
        phase_phi: 5.5859976,
    },
    Element {
        z: 86,
        symbol: "Rn",
        name: "Radon",
        name_ru: "Радон",
        atomic_mass: 222.0,
        electronegativity: 2.2,
        group: 18,
        period: 6,
        block: ChemBlock::P,
        covalent_radius_pm: 2e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 10.7,
        electron_config: "[Xe] 4f14 5d10 6s2 6p6",
        archetype: ChemArchetype::NobleGasP6,
        phase_phi: 0.92084627,
    },
    Element {
        z: 87,
        symbol: "Fr",
        name: "Francium",
        name_ru: "Франций",
        atomic_mass: 223.0,
        electronegativity: 0.7,
        group: 1,
        period: 7,
        block: ChemBlock::S,
        covalent_radius_pm: 3e+02,
        vdw_radius_pm: 3e+02,
        ionization_energy_ev: 4.07,
        electron_config: "[Rn] 7s1",
        archetype: ChemArchetype::AlkaliS1,
        phase_phi: 2.5388803,
    },
    Element {
        z: 88,
        symbol: "Ra",
        name: "Radium",
        name_ru: "Радий",
        atomic_mass: 226.0,
        electronegativity: 0.9,
        group: 2,
        period: 7,
        block: ChemBlock::S,
        covalent_radius_pm: 2e+02,
        vdw_radius_pm: 3e+02,
        ionization_energy_ev: 5.28,
        electron_config: "[Rn] 7s2",
        archetype: ChemArchetype::AlkalineEarthS2,
        phase_phi: 4.1569143,
    },
    Element {
        z: 89,
        symbol: "Ac",
        name: "Actinium",
        name_ru: "Актиний",
        atomic_mass: 227.0,
        electronegativity: 1.1,
        group: 3,
        period: 7,
        block: ChemBlock::F,
        covalent_radius_pm: 2e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 5.17,
        electron_config: "[Rn] 6d1 7s2",
        archetype: ChemArchetype::Actinide5F,
        phase_phi: 5.7749482,
    },
    Element {
        z: 90,
        symbol: "Th",
        name: "Thorium",
        name_ru: "Торий",
        atomic_mass: 232.038,
        electronegativity: 1.3,
        group: 3,
        period: 7,
        block: ChemBlock::F,
        covalent_radius_pm: 2e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 6.31,
        electron_config: "[Rn] 6d2 7s2",
        archetype: ChemArchetype::Actinide5F,
        phase_phi: 1.1097969,
    },
    Element {
        z: 91,
        symbol: "Pa",
        name: "Protactinium",
        name_ru: "Протактиний",
        atomic_mass: 231.036,
        electronegativity: 1.5,
        group: 3,
        period: 7,
        block: ChemBlock::F,
        covalent_radius_pm: 2e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 5.89,
        electron_config: "[Rn] 5f2 6d1 7s2",
        archetype: ChemArchetype::Actinide5F,
        phase_phi: 2.7278309,
    },
    Element {
        z: 92,
        symbol: "U",
        name: "Uranium",
        name_ru: "Уран",
        atomic_mass: 238.029,
        electronegativity: 1.4,
        group: 3,
        period: 7,
        block: ChemBlock::F,
        covalent_radius_pm: 2e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 6.19,
        electron_config: "[Rn] 5f3 6d1 7s2",
        archetype: ChemArchetype::Actinide5F,
        phase_phi: 4.3458649,
    },
    Element {
        z: 93,
        symbol: "Np",
        name: "Neptunium",
        name_ru: "Нептуний",
        atomic_mass: 237.0,
        electronegativity: 1.4,
        group: 3,
        period: 7,
        block: ChemBlock::F,
        covalent_radius_pm: 2e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 6.27,
        electron_config: "[Rn] 5f4 6d1 7s2",
        archetype: ChemArchetype::Actinide5F,
        phase_phi: 5.9638989,
    },
    Element {
        z: 94,
        symbol: "Pu",
        name: "Plutonium",
        name_ru: "Плутоний",
        atomic_mass: 244.0,
        electronegativity: 1.3,
        group: 3,
        period: 7,
        block: ChemBlock::F,
        covalent_radius_pm: 2e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 6.03,
        electron_config: "[Rn] 5f6 7s2",
        archetype: ChemArchetype::Actinide5F,
        phase_phi: 1.2987476,
    },
    Element {
        z: 95,
        symbol: "Am",
        name: "Americium",
        name_ru: "Америций",
        atomic_mass: 243.0,
        electronegativity: 1.1,
        group: 3,
        period: 7,
        block: ChemBlock::F,
        covalent_radius_pm: 2e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 5.97,
        electron_config: "[Rn] 5f7 7s2",
        archetype: ChemArchetype::Actinide5F,
        phase_phi: 2.9167816,
    },
    Element {
        z: 96,
        symbol: "Cm",
        name: "Curium",
        name_ru: "Кюрий",
        atomic_mass: 247.0,
        electronegativity: 1.3,
        group: 3,
        period: 7,
        block: ChemBlock::F,
        covalent_radius_pm: 2e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 5.99,
        electron_config: "[Rn] 5f7 6d1 7s2",
        archetype: ChemArchetype::Actinide5F,
        phase_phi: 4.5348155,
    },
    Element {
        z: 97,
        symbol: "Bk",
        name: "Berkelium",
        name_ru: "Берклий",
        atomic_mass: 247.0,
        electronegativity: 1.3,
        group: 3,
        period: 7,
        block: ChemBlock::F,
        covalent_radius_pm: 2e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 6.2,
        electron_config: "[Rn] 5f9 7s2",
        archetype: ChemArchetype::Actinide5F,
        phase_phi: 6.1528495,
    },
    Element {
        z: 98,
        symbol: "Cf",
        name: "Californium",
        name_ru: "Калифорний",
        atomic_mass: 251.0,
        electronegativity: 1.3,
        group: 3,
        period: 7,
        block: ChemBlock::F,
        covalent_radius_pm: 2e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 6.28,
        electron_config: "[Rn] 5f10 7s2",
        archetype: ChemArchetype::Actinide5F,
        phase_phi: 1.4876982,
    },
    Element {
        z: 99,
        symbol: "Es",
        name: "Einsteinium",
        name_ru: "Эйнштейний",
        atomic_mass: 252.0,
        electronegativity: 1.3,
        group: 3,
        period: 7,
        block: ChemBlock::F,
        covalent_radius_pm: 2e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 6.42,
        electron_config: "[Rn] 5f11 7s2",
        archetype: ChemArchetype::Actinide5F,
        phase_phi: 3.1057322,
    },
    Element {
        z: 100,
        symbol: "Fm",
        name: "Fermium",
        name_ru: "Фермий",
        atomic_mass: 257.0,
        electronegativity: 1.3,
        group: 3,
        period: 7,
        block: ChemBlock::F,
        covalent_radius_pm: 2e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 6.5,
        electron_config: "[Rn] 5f12 7s2",
        archetype: ChemArchetype::Actinide5F,
        phase_phi: 4.7237662,
    },
    Element {
        z: 101,
        symbol: "Md",
        name: "Mendelevium",
        name_ru: "Менделевий",
        atomic_mass: 258.0,
        electronegativity: 1.3,
        group: 3,
        period: 7,
        block: ChemBlock::F,
        covalent_radius_pm: 2e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 6.58,
        electron_config: "[Rn] 5f13 7s2",
        archetype: ChemArchetype::Actinide5F,
        phase_phi: 0.058614877,
    },
    Element {
        z: 102,
        symbol: "No",
        name: "Nobelium",
        name_ru: "Нобелий",
        atomic_mass: 259.0,
        electronegativity: 1.3,
        group: 3,
        period: 7,
        block: ChemBlock::F,
        covalent_radius_pm: 2e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 6.65,
        electron_config: "[Rn] 5f14 7s2",
        archetype: ChemArchetype::Actinide5F,
        phase_phi: 1.6766489,
    },
    Element {
        z: 103,
        symbol: "Lr",
        name: "Lawrencium",
        name_ru: "Лоуренсий",
        atomic_mass: 266.0,
        electronegativity: 1.3,
        group: 3,
        period: 7,
        block: ChemBlock::D,
        covalent_radius_pm: 2e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 4.9,
        electron_config: "[Rn] 5f14 7s2 7p1",
        archetype: ChemArchetype::Actinide5F,
        phase_phi: 3.2946829,
    },
    Element {
        z: 104,
        symbol: "Rf",
        name: "Rutherfordium",
        name_ru: "Резерфордий",
        atomic_mass: 267.0,
        electronegativity: 0.0,
        group: 4,
        period: 7,
        block: ChemBlock::D,
        covalent_radius_pm: 2e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 6.0,
        electron_config: "[Rn] 5f14 6d2 7s2",
        archetype: ChemArchetype::TransitionDBlock,
        phase_phi: 4.9127168,
    },
    Element {
        z: 105,
        symbol: "Db",
        name: "Dubnium",
        name_ru: "Дубний",
        atomic_mass: 268.0,
        electronegativity: 0.0,
        group: 5,
        period: 7,
        block: ChemBlock::D,
        covalent_radius_pm: 1e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 6.8,
        electron_config: "[Rn] 5f14 6d3 7s2",
        archetype: ChemArchetype::TransitionDBlock,
        phase_phi: 0.24756552,
    },
    Element {
        z: 106,
        symbol: "Sg",
        name: "Seaborgium",
        name_ru: "Сиборгий",
        atomic_mass: 269.0,
        electronegativity: 0.0,
        group: 6,
        period: 7,
        block: ChemBlock::D,
        covalent_radius_pm: 1e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 7.5,
        electron_config: "[Rn] 5f14 6d4 7s2",
        archetype: ChemArchetype::TransitionDBlock,
        phase_phi: 1.8655995,
    },
    Element {
        z: 107,
        symbol: "Bh",
        name: "Bohrium",
        name_ru: "Борий",
        atomic_mass: 270.0,
        electronegativity: 0.0,
        group: 7,
        period: 7,
        block: ChemBlock::D,
        covalent_radius_pm: 1e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 7.7,
        electron_config: "[Rn] 5f14 6d5 7s2",
        archetype: ChemArchetype::TransitionDBlock,
        phase_phi: 3.4836335,
    },
    Element {
        z: 108,
        symbol: "Hs",
        name: "Hassium",
        name_ru: "Хассий",
        atomic_mass: 277.0,
        electronegativity: 0.0,
        group: 8,
        period: 7,
        block: ChemBlock::D,
        covalent_radius_pm: 1e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 7.8,
        electron_config: "[Rn] 5f14 6d6 7s2",
        archetype: ChemArchetype::TransitionDBlock,
        phase_phi: 5.1016675,
    },
    Element {
        z: 109,
        symbol: "Mt",
        name: "Meitnerium",
        name_ru: "Мейтнерий",
        atomic_mass: 278.0,
        electronegativity: 0.0,
        group: 9,
        period: 7,
        block: ChemBlock::D,
        covalent_radius_pm: 1e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 8.0,
        electron_config: "[Rn] 5f14 6d7 7s2",
        archetype: ChemArchetype::TransitionDBlock,
        phase_phi: 0.43651617,
    },
    Element {
        z: 110,
        symbol: "Ds",
        name: "Darmstadtium",
        name_ru: "Дармштадтий",
        atomic_mass: 281.0,
        electronegativity: 0.0,
        group: 10,
        period: 7,
        block: ChemBlock::D,
        covalent_radius_pm: 1e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 9.6,
        electron_config: "[Rn] 5f14 6d9 7s1",
        archetype: ChemArchetype::TransitionDBlock,
        phase_phi: 2.0545502,
    },
    Element {
        z: 111,
        symbol: "Rg",
        name: "Roentgenium",
        name_ru: "Рентгений",
        atomic_mass: 282.0,
        electronegativity: 0.0,
        group: 11,
        period: 7,
        block: ChemBlock::D,
        covalent_radius_pm: 1e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 10.4,
        electron_config: "[Rn] 5f14 6d10 7s1",
        archetype: ChemArchetype::TransitionDBlock,
        phase_phi: 3.6725842,
    },
    Element {
        z: 112,
        symbol: "Cn",
        name: "Copernicium",
        name_ru: "Коперниций",
        atomic_mass: 285.0,
        electronegativity: 0.0,
        group: 12,
        period: 7,
        block: ChemBlock::D,
        covalent_radius_pm: 1e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 11.9,
        electron_config: "[Rn] 5f14 6d10 7s2",
        archetype: ChemArchetype::TransitionDBlock,
        phase_phi: 5.2906181,
    },
    Element {
        z: 113,
        symbol: "Nh",
        name: "Nihonium",
        name_ru: "Нихоний",
        atomic_mass: 286.0,
        electronegativity: 0.0,
        group: 13,
        period: 7,
        block: ChemBlock::P,
        covalent_radius_pm: 1e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 7.3,
        electron_config: "[Rn] 5f14 6d10 7s2 7p1",
        archetype: ChemArchetype::PostTransition,
        phase_phi: 0.62546682,
    },
    Element {
        z: 114,
        symbol: "Fl",
        name: "Flerovium",
        name_ru: "Флеровий",
        atomic_mass: 289.0,
        electronegativity: 0.0,
        group: 14,
        period: 7,
        block: ChemBlock::P,
        covalent_radius_pm: 1e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 8.5,
        electron_config: "[Rn] 5f14 6d10 7s2 7p2",
        archetype: ChemArchetype::PostTransition,
        phase_phi: 2.2435008,
    },
    Element {
        z: 115,
        symbol: "Mc",
        name: "Moscovium",
        name_ru: "Московий",
        atomic_mass: 290.0,
        electronegativity: 0.0,
        group: 15,
        period: 7,
        block: ChemBlock::P,
        covalent_radius_pm: 2e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 5.6,
        electron_config: "[Rn] 5f14 6d10 7s2 7p3",
        archetype: ChemArchetype::PostTransition,
        phase_phi: 3.8615348,
    },
    Element {
        z: 116,
        symbol: "Lv",
        name: "Livermorium",
        name_ru: "Ливерморий",
        atomic_mass: 293.0,
        electronegativity: 0.0,
        group: 16,
        period: 7,
        block: ChemBlock::P,
        covalent_radius_pm: 2e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 7.1,
        electron_config: "[Rn] 5f14 6d10 7s2 7p4",
        archetype: ChemArchetype::PostTransition,
        phase_phi: 5.4795688,
    },
    Element {
        z: 117,
        symbol: "Ts",
        name: "Tennessine",
        name_ru: "Теннессин",
        atomic_mass: 294.0,
        electronegativity: 0.0,
        group: 17,
        period: 7,
        block: ChemBlock::P,
        covalent_radius_pm: 2e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 7.7,
        electron_config: "[Rn] 5f14 6d10 7s2 7p5",
        archetype: ChemArchetype::HalogenP5,
        phase_phi: 0.81441747,
    },
    Element {
        z: 118,
        symbol: "Og",
        name: "Oganesson",
        name_ru: "Оганесон",
        atomic_mass: 294.0,
        electronegativity: 0.0,
        group: 18,
        period: 7,
        block: ChemBlock::P,
        covalent_radius_pm: 2e+02,
        vdw_radius_pm: 2e+02,
        ionization_energy_ev: 8.8,
        electron_config: "[Rn] 5f14 6d10 7s2 7p6",
        archetype: ChemArchetype::NobleGasP6,
        phase_phi: 2.4324515,
    },
];

/// Швидкий пошук елемента за атомним номером Z (1..118)
pub fn get_element_by_z(z: u8) -> Option<&'static Element> {
    if z >= 1 && z <= 118 {
        Some(&PERIODIC_TABLE[(z - 1) as usize])
    } else {
        None
    }
}

/// Швидкий пошук елемента за хімічним символом (case-insensitive)
pub fn get_element_by_symbol(sym: &str) -> Option<&'static Element> {
    let sym_trimmed = sym.trim();
    PERIODIC_TABLE.iter().find(|e| e.symbol.eq_ignore_ascii_case(sym_trimmed))
}

/// Квантовий стан хімічного зв'язку між двома елементами
#[derive(Debug, Clone, PartialEq)]
pub struct ChemicalBond {
    pub elem_a: &'static Element,
    pub elem_b: &'static Element,
    pub delta_chi: f64,
    pub bond_type: BondType,
    pub trit: i8,
    pub phase_resonance: f64,
    pub estimated_length_pm: f32,
}

/// Обчислення хімічного зв'язку між двома елементами
pub fn calculate_bond(elem_a: &'static Element, elem_b: &'static Element) -> ChemicalBond {
    let delta_chi = (elem_a.electronegativity - elem_b.electronegativity).abs();
    let estimated_length_pm = elem_a.covalent_radius_pm + elem_b.covalent_radius_pm;
    let phase_diff = elem_a.phase_phi - elem_b.phase_phi;
    let phase_resonance = (phase_diff).cos();

    // Перевірка на інертні гази
    if elem_a.archetype == ChemArchetype::NobleGasP6 || elem_b.archetype == ChemArchetype::NobleGasP6 {
        return ChemicalBond {
            elem_a,
            elem_b,
            delta_chi,
            bond_type: BondType::Inert,
            trit: 0,
            phase_resonance,
            estimated_length_pm,
        };
    }

    // Перевірка на металічний зв'язок
    if elem_a.is_metal() && elem_b.is_metal() {
        return ChemicalBond {
            elem_a,
            elem_b,
            delta_chi,
            bond_type: BondType::Metallic,
            trit: 0,
            phase_resonance,
            estimated_length_pm,
        };
    }

    // Класифікація за різницею електронегативності Полінга:
    // Трит 0: Неполярний ковалентний (Δχ < 0.4)
    // Трит +1: Полярний ковалентний (0.4 <= Δχ <= 2.0)
    // Трит -1: Йонний зв'язок (Δχ > 2.0)
    let (bond_type, trit) = if delta_chi < 0.4 {
        (BondType::NonPolarCovalent, 0i8)
    } else if delta_chi <= 2.0 {
        (BondType::PolarCovalent, 1i8)
    } else {
        (BondType::Ionic, -1i8)
    };

    ChemicalBond {
        elem_a,
        elem_b,
        delta_chi,
        bond_type,
        trit,
        phase_resonance,
        estimated_length_pm,
    }
}

/// Результат стехіометричного розбору молекулярної формули
#[derive(Debug, Clone, PartialEq)]
pub struct ParsedMolecule {
    pub counts: BTreeMap<&'static str, usize>,
    pub molar_mass: f64,
    pub total_electrons: usize,
    pub mass_fractions: BTreeMap<&'static str, f64>,
}

/// Стехіометричний парсер молекулярних формул (підтримує H2O, H2SO4, Fe2(SO4)3, K4[Fe(CN)6], CH3COOH тощо)
pub fn parse_chemical_formula(formula: &str) -> Result<ParsedMolecule, String> {
    let formula = formula.trim();
    if formula.is_empty() {
        return Err("Порожня хімічна формула".into());
    }

    let mut stack: Vec<BTreeMap<&'static str, usize>> = vec![BTreeMap::new()];
    let chars: Vec<char> = formula.chars().collect();
    let mut i = 0;
    let n = chars.len();

    while i < n {
        let c = chars[i];
        if c == '(' || c == '[' || c == '{' {
            stack.push(BTreeMap::new());
            i += 1;
        } else if c == ')' || c == ']' || c == '}' {
            i += 1;
            // Зчитування множника після дужки
            let mut num_str = String::new();
            while i < n && chars[i].is_ascii_digit() {
                num_str.push(chars[i]);
                i += 1;
            }
            let multiplier: usize = if num_str.is_empty() {
                1
            } else {
                num_str.parse().map_err(|e| format!("Некоректний індекс: {e}"))?
            };

            let group_counts = stack.pop().ok_or_else(|| "Незбалансовані дужки".to_string())?;
            let current = stack.last_mut().ok_or_else(|| "Помилка стека формули".to_string())?;
            for (elem, cnt) in group_counts {
                *current.entry(elem).or_insert(0) += cnt * multiplier;
            }
        } else if c.is_ascii_uppercase() {
            let mut sym = String::new();
            sym.push(c);
            i += 1;
            if i < n && chars[i].is_ascii_lowercase() {
                sym.push(chars[i]);
                i += 1;
            }
            let elem = get_element_by_symbol(&sym)
                .ok_or_else(|| format!("Невідомий хімічний елемент: '{sym}'"))?;

            // Зчитування числа атомів
            let mut num_str = String::new();
            while i < n && chars[i].is_ascii_digit() {
                num_str.push(chars[i]);
                i += 1;
            }
            let count: usize = if num_str.is_empty() {
                1
            } else {
                num_str.parse().map_err(|e| format!("Некоректний індекс: {e}"))?
            };

            let current = stack.last_mut().ok_or_else(|| "Помилка стека формули".to_string())?;
            *current.entry(elem.symbol).or_insert(0) += count;
        } else if c.is_whitespace() || c == '·' || c == '*' {
            i += 1;
        } else {
            return Err(format!("Невідомий символ у формулі на позиції {i}: '{c}'"));
        }
    }

    if stack.len() != 1 {
        return Err("Незбалансовані відкриті дужки у хімічній формулі".into());
    }

    let counts = stack.pop().unwrap();
    if counts.is_empty() {
        return Err("Формула не містить розпізнаних елементів".into());
    }

    let mut molar_mass = 0.0;
    let mut total_electrons = 0;

    for (&sym, &cnt) in &counts {
        let elem = get_element_by_symbol(sym).unwrap();
        molar_mass += elem.atomic_mass * (cnt as f64);
        total_electrons += (elem.z as usize) * cnt;
    }

    let mut mass_fractions = BTreeMap::new();
    for (&sym, &cnt) in &counts {
        let elem = get_element_by_symbol(sym).unwrap();
        let fraction = (elem.atomic_mass * (cnt as f64)) / molar_mass;
        mass_fractions.insert(sym, fraction);
    }

    Ok(ParsedMolecule {
        counts,
        molar_mass,
        total_electrons,
        mass_fractions,
    })
}

/// 12x12 Матриця переходів між квантово-хімічними архетипами J = A - A^T
#[derive(Debug, Clone)]
pub struct ChemArchetypeMatrix {
    pub weights: [[i8; NUM_CHEM_ARCHETYPES]; NUM_CHEM_ARCHETYPES],
}

impl ChemArchetypeMatrix {
    pub fn build() -> Self {
        let mut weights = [[0i8; NUM_CHEM_ARCHETYPES]; NUM_CHEM_ARCHETYPES];
        for i in 0..NUM_CHEM_ARCHETYPES {
            for j in 0..NUM_CHEM_ARCHETYPES {
                if i == j {
                    weights[i][j] = 0;
                } else {
                    let phase_diff = ((i as f64 - j as f64) * PHI).sin();
                    if phase_diff > 0.3 {
                        weights[i][j] = 1;
                        weights[j][i] = -1;
                    } else if phase_diff < -0.3 {
                        weights[i][j] = -1;
                        weights[j][i] = 1;
                    }
                }
            }
        }
        Self { weights }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_periodic_table_count() {
        assert_eq!(PERIODIC_TABLE.len(), 118);
        assert_eq!(PERIODIC_TABLE[0].symbol, "H");
        assert_eq!(PERIODIC_TABLE[117].symbol, "Og");
    }

    #[test]
    fn test_lookup_element() {
        let c = get_element_by_symbol("C").unwrap();
        assert_eq!(c.z, 6);
        assert_eq!(c.atomic_mass, 12.011);
        assert_eq!(c.archetype, ChemArchetype::OrganicLifeNonmetal);

        let fe = get_element_by_symbol("fe").unwrap();
        assert_eq!(fe.z, 26);
        assert!(fe.is_metal());
    }

    #[test]
    fn test_chemical_bonds() {
        let h = get_element_by_symbol("H").unwrap();
        let o = get_element_by_symbol("O").unwrap();
        let na = get_element_by_symbol("Na").unwrap();
        let cl = get_element_by_symbol("Cl").unwrap();
        let c = get_element_by_symbol("C").unwrap();

        // O-H: Полярний ковалентний (Δχ = 3.44 - 2.20 = 1.24) -> Трит +1
        let bond_oh = calculate_bond(o, h);
        assert_eq!(bond_oh.bond_type, BondType::PolarCovalent);
        assert_eq!(bond_oh.trit, 1);

        // Na-Cl: Йонний (Δχ = 3.16 - 0.93 = 2.23) -> Трит -1
        let bond_nacl = calculate_bond(na, cl);
        assert_eq!(bond_nacl.bond_type, BondType::Ionic);
        assert_eq!(bond_nacl.trit, -1);

        // C-H: Неполярний ковалентний (Δχ = 2.55 - 2.20 = 0.35) -> Трит 0
        let bond_ch = calculate_bond(c, h);
        assert_eq!(bond_ch.bond_type, BondType::NonPolarCovalent);
        assert_eq!(bond_ch.trit, 0);
    }

    #[test]
    fn test_formula_parsing() {
        // H2O
        let h2o = parse_chemical_formula("H2O").unwrap();
        assert_eq!(*h2o.counts.get("H").unwrap(), 2);
        assert_eq!(*h2o.counts.get("O").unwrap(), 1);
        assert!((h2o.molar_mass - 18.015).abs() < 0.01);
        assert_eq!(h2o.total_electrons, 10);

        // Fe2(SO4)3
        let fe2so4_3 = parse_chemical_formula("Fe2(SO4)3").unwrap();
        assert_eq!(*fe2so4_3.counts.get("Fe").unwrap(), 2);
        assert_eq!(*fe2so4_3.counts.get("S").unwrap(), 3);
        assert_eq!(*fe2so4_3.counts.get("O").unwrap(), 12);
        assert!((fe2so4_3.molar_mass - 399.88).abs() < 0.1);

        // Ca(OH)2
        let caoh2 = parse_chemical_formula("Ca(OH)2").unwrap();
        assert_eq!(*caoh2.counts.get("Ca").unwrap(), 1);
        assert_eq!(*caoh2.counts.get("O").unwrap(), 2);
        assert_eq!(*caoh2.counts.get("H").unwrap(), 2);
    }
}
